version: '3'
services:
  mongodb:
    image: mongo:4.2
    container_name: "mmg-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017